<div class="my-account">
	<div class="dashboard">
		<div class="page-title">
			<h1>
			<?php echo $this->__('Bidding History')?>
			</h1>
		</div>
		<div class="fieldset">
			<h2 class="legend">
			<?php echo $this->__('Products List')?>
			</h2>
			<?php if  ($this->getBiddingProducts()->getData()): ?>
			<table class="data-table" id="my-orders-table">
				<thead>
					<tr class="first last">
						<th><?php echo $this->__('Product Name')?>
						</th>
						<th><?php echo $this->__('Action')?>
						</th>
					</tr>
				</thead>
				<tbody>
				<?php
				foreach ($this->getBiddingProducts() as $_product):
					$pro = Mage::getModel('catalog/product')->load($_product->getProductId());
				?>
					<tr>
						<td><?php echo $pro->getName() ?></td>
						<td><a href="<?php echo Mage::getUrl('bidding/bidding/preview', array('id' => $pro->getId()))?>"><?php echo $this->__('View Details')?></a></td>
					</tr>
					<?php
					endforeach;
					?>
				</tbody>
			</table>
			<?php else: ?>
			<p>
			<?php echo $this->__('You didn\'t have any product till now')?>
			</p>
			<?php endif; ?>
		</div>
	</div>
</div>
