<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getCollection(); ?>
<div class="my-account">
	<div class="dashboard">
		<div class="page-title">
			<h1>
			<?php echo $this->__('Product Bidding History')?>
			</h1>
		</div>
	</div>
	<div class="fieldset">
			<h2 class="legend">
			<?php 
			$_pro = Mage::getModel('catalog/product')->load($this->getRequest()->getParam('id'));
			echo $this->__('Product Details For:') . ' ' . $_pro->getName();
			?>
			</h2>
			<?php if  ($collection->getSize()): ?>
			<?php echo $this->getPagerHtml(); ?>
			<table class="data-table" id="my-orders-table">
				<thead>
					<tr class="first last">
						<th><?php echo $this->__('Price')?>
						</th>
						<th><?php echo $this->__('New Price')?>
						</th>
						<th><?php echo $this->__('Date')?>
						</th>
					</tr>
				</thead>
				<tbody>
				<?php
				foreach ($collection as $_product):
				?>
					<tr>
						<td><?php echo Mage::helper('core')->currency($_product->getPrice())?></td>
						<td><?php echo Mage::helper('core')->currency($_product->getNewPrice())?></td>
						<td><?php echo $_product->getBidDate() ?></td>
					</tr>
					<?php
					endforeach;
					?>
				</tbody>
			</table>
			<?php echo $this->getPagerHtml(); ?>
			<?php else: ?>
			<p>
			<?php echo $this->__('This product not valid')?>
			</p>
			<?php endif; ?>
		</div>
</div>
<div class="buttons-set">
	<p class="back-link">
		<a href="<?php echo Mage::getUrl('bidding/bidding') ?>"><small><< </small>
		<?php echo $this->__('Back to history'); ?> </a>
	</p>
</div>
