<div class="product-view bidders-list">
	<div class="product-essential">
		<div class="title">
			<h1><?php echo $this->__('Bid History')?></h1>
		</div>
		<div class="content">
			<table border="0" cellspacing="0" cellpadding="0" id="bidder-table-<?php echo $this->getRequest()->getParam('id')?>">
				<thead>
					<tr>
						<td><?php echo $this->__('Bid')?></td>
						<td><?php echo $this->__('Bidder')?></td>
					</tr>
				</thead>
				<tbody>
					<?php 
					$bidders = $this->getBidders();
					foreach ($bidders as $bidder):
					?>
					<tr>
						<td><?php echo Mage::helper('core')->currency($bidder->getNewPrice()) ?></td>
						<td><?php echo Mage::getModel('customer/customer')->load($bidder->getCustomerId())->getName() ?></td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>