<div class="g2pMessage"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('gate2play')->toHtml() ?></div>
<style type="text/css">
form {
    display: block;
}
</style>
<script type="text/javascript" src="<?php echo $this->getJs(); ?>"></script>
<div id="gate2play"></div>
<form action="<?php echo $this->getStatusUrl();?>" id="<?php echo $this->getTokenID(); ?>">
<?php echo $this->getBrands(); ?>
</form>