<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_pointsHistory = $this->getPointsHistory(); ?>
<div class="my-account">
	<div class="dashboard">
		<div class="page-title">
			<h1>
				<?php echo $this->__('Points Dashboard')?>
			</h1>
		</div>
		<div class="fieldset">
			<h2 class="legend">
				<?php echo $this->__('Balance')?>
			</h2>
			<ul class="form-list">
				<li class="control"><label><?php echo $this->__('Your current points:')?>
						<span style=""><?php echo $this->getPoints()->getBalance(); ?></span></label>
				</li>
			</ul>
		</div>
		<div class="fieldset">
			<h2 class="legend">
				<?php echo $this->__('Points Purchasing History')?>
			</h2>
			<?php echo $this->getPagerHtml(); ?>
			<?php if($_pointsHistory->getSize()): ?>
			<table class="data-table" id="my-orders-table">
				<col width="1" />
				<col width="1" />
				<col />
				<col width="1" />
				<col width="1" />
				<col width="1" />
				<thead>
					<tr>
						<th><?php echo $this->__('Order #') ?></th>
						<th><?php echo $this->__('Date') ?></th>
						<th><?php echo $this->__('Balance') ?></th>
						<th>&nbsp;</th>
					</tr>
				</thead>
				<tbody>
					<?php $_odd = ''; ?>
					<?php foreach ($_pointsHistory as $_pointHistory): ?>
					<tr>
						<td><?php echo $_pointHistory->getOrderNumber() ?></td>
						<td><span class="nobr"><?php echo $this->formatDate($_pointHistory->getDate()) ?></span></td>
						<td><?php echo $_pointHistory->getBalance() ?></td>
						<td class="a-center"><span class="nobr"><a href="<?php echo Mage::getUrl('sales/order/view', array('order_id' => $_pointHistory->getOrderId())) ?>"><?php echo $this->__('View Order') ?></a>
						</span>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
			<script type="text/javascript">decorateTable('my-orders-table');</script>
			<?php echo $this->getPagerHtml(); ?>
			<?php else: ?>
			<p>
				<?php echo $this->__('You have placed no point.'); ?>
			</p>
			<?php endif; ?>
		</div>
	</div>
</div>
