<?php
$_products = $this->getProducts();
if ($_products->count()):
	?>
<script type="text/javascript">
<!--
window.onload = function () {
	window.socket = io.connect('http://www.auctionsvip.com:3700');
	socket.on('message', function (data) {
		jQuery("#price-box-" + data.PI).html(data.price);
		jQuery("#price-box-" + data.PI).parent().parent().addClass('highlight').delay(500).queue(
			function(next){
				jQuery("#price-box-" + data.PI).parent().parent().removeClass('highlight');
				next();
			}
			);

		jQuery(".biddername" + data.PI).html(data.bidder);
		jQuery(".biddername" + data.PI).parent().parent().addClass('highlight').delay(500).queue(
			function(next){
				jQuery(".biddername" + data.PI).parent().parent().removeClass('highlight');
				next();
			}
			);
	});
}
//-->
</script>
<div id="messages_product_view">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>
<div class="container homeProducts">
	<div class="row">
		<?php
		$i = 1;
		foreach ($_products as $_product):
			$_productDate = date('Y/m/d H:i:s',strtotime($_product->getEndBiddingDate()));
		?>
		<div class="item span3"><a
			href="<?php echo $this->getUrl('bidding/product/view', array('id'=>$_product->getId())) ?>"
			class="product-image"> <img
			src="<?php echo $_product->getImageUrl() ?>" />
		</a>
		<h1 class="product-name">
			<a
			href="<?php echo $this->getUrl('bidding/product/view', array('id'=>$_product->getId())) ?>"
			title="<?php $_product->getName() ?>"><?php echo $_product->getName() ?>
		</a>
	</h1>
	<div class="price-box" style="display:none">
		<span class="reqular-price"> <span><?php echo $this->__('Open Bid Price:') . ' '?>
		</span><span class="open-price"><?php echo Mage::helper('core')->currency($_product->getOpeningPrice()); ?>
	</span> </span>
</div>
<div class="price-box" style="display:none">
	<span class="reqular-price"> <span><?php echo $this->__('Close Price:') . ' '?>
	</span><span class="open-price"><?php echo Mage::helper('core')->currency($_product->getPrice()); ?>
</span> </span>
</div>
<div class="price-box" style="display:none">
	<span class="reqular-price"> <span><?php echo $this->__('Retail Price:') . ' '?>
	</span><span class="open-price"><?php echo Mage::helper('core')->currency($_product->getRetailPrice()); ?>
</span> </span>
</div>
<div class="countdown" style="display:none">
	<p class="currentvalue">
		<span ></span>
	</p>
</div>



<div class="bidOptions">
	<div class="section left">
		<div>Timer : <span id="clock<?php echo $i; ?>"></span></div>
		<div>	<div class="price" id="price<?php echo $_product->getId() ?>">
		<span id="price-box-<?php echo $_product->getId()?>"><?php echo Mage::helper('core')->currency($_product->getCurrentPrice()) ?>
		</span>
	</div></div>
	</div>
			<?php
		$customerSession = $this->getCustomerSession();
		if(!$customerSession->isLoggedIn())
		{
			?><div class="section center">
			<button type="button" title="bid" class="button bidButton"
			id="button<?php echo $_product->getId() ?>"
			onclick="javascript:alert('Please login')">
			<?php echo $this->__('Bid')?>
		</button>
		
		</div>
		<?php
	}
	else
	{
		?>
		<div class="section center">
		<form action="#" method="post"
		class="formbid<?php echo $_product->getId() ?>"
		id="formbid<?php echo $_product->getId() ?>">
		<?php echo $this->getBlockHtml('formkey') ?>
		<input type="hidden" name="productId"
		value="<?php echo $_product->getId() ?>" />
		<button type="submit" title="bid" class="button bidButton"
		id="button<?php echo $_product->getId() ?>">
		<?php echo $this->__('Bid')?> 
	</button>

</form>
</div>
	
	<?php $bidder = $this->getCurrentBidder($_product->getId());
	if ($bidder):
		$bidder = Mage::getModel('customer/customer')->load($bidder[0]['customer_id'])->getName();
	?>
	<div class="section right">
		<div><?php echo $this->__('Bidder')?></div>
		<div><?php echo $bidder ?></div>
	</div>
<?php endif; ?>

</div>


<div>
	
	</div> <script>
	jQuery("#clock" + <?php echo $i; ?>).countdown("<?php echo $_productDate ?>")
	.on('update.countdown', function(event){
		var format = '%H:%M:%S';
		if (event.offset.days > 0){
			format = '%-d day%!d ' + format;
		}
		if (event.offset.weeks > 0){
			format = '%-w week%!w ' + format;
		}
		jQuery("#clock" + <?php echo $i; ?>).html(event.strftime(format));
	})
	.on('finish.countdown', function(event) {
		location.reload();
	});
	</script>

<script>
jQuery("#formbid<?php echo $_product->getId() ?>").submit(function(event) {
	event.preventDefault();
	jQuery("#button<?php echo $_product->getId() ?>").attr("disabled", true);
	jQuery("#button<?php echo $_product->getId() ?>").fadeOut();
	var values = jQuery(this).serialize();
	jQuery.ajax({
		url: "<?php echo $this->getUrl('bidding/index/bidPost') ?>",
		type: "post",
		data: values,
		success: function(resp){
			resp = jQuery.parseJSON(resp);
			if(resp.action == 'true')
			{
				jQuery("#button<?php echo $_product->getId() ?>").attr("disabled", false); 
				jQuery("#button<?php echo $_product->getId() ?>").delay(500).fadeIn(50);
				window.socket.emit('send', { message: 1, PI: resp.PI, price: resp.price, bidder: resp.bidder, bidderTable: resp.bidderTable });
				if (resp.reload == 'true')
				{
					location.reload();
				}

			}
			else
			{
				location.reload();
			}
		},
		error: function(){
			alert('faild');
		}
	});
});
</script>
<?php
}
?>
</div>

</div>
<?php
$i++;
endforeach;
?>
</div>
</div>
<?php
else :
	?>
<p class="note-msg">
	<?php echo $this->__('There are no products for bid right now')?>
</p>
<?php
endif;
?>
