<?php 
$_products = $this->getProducts();
if ($_products->count()):
?>
<script type="text/javascript">
<!--
window.onload = function () {
	window.socket = io.connect('http://127.0.0.1:3700');
	socket.on('message', function (data) {
		jQuery("#price-box-" + data.PI).html(data.price);
		jQuery("#price-box-" + data.PI).addClass('highlight').delay(500).queue(
		  function(next){
			jQuery("#price-box-" + data.PI).removeClass('highlight');
			next();
			}
		 );

		  jQuery(".biddername" + data.PI).html(data.bidder);
		  jQuery(".biddername" + data.PI).addClass('highlight').delay(500).queue(
				  function(next){
					  jQuery(".biddername" + data.PI).removeClass('highlight');
					  next();
				}
		   );
	});
}
//-->
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<ul class="col1-layout products-grid">
	<?php
	$i = 1;
	foreach ($_products as $_product):
	$_productDate = date('Y/m/d H:i:s',strtotime($_product->getEndBiddingDate()));
	?>
	<li class="item"><a href="<?php echo $this->getUrl('bidding/product/view', array('id'=>$_product->getId())) ?>"
		class="product-image"> <img
			src="<?php echo $_product->getImageUrl() ?>" width="135" height="135" />
	</a>
		<h1 class="product-name">
			<a href="<?php echo $this->getUrl('bidding/product/view', array('id'=>$_product->getId())) ?>"
				title="<?php $_product->getName() ?>"><?php echo $_product->getName() ?>
			</a>
		</h1>
		<div class="price-box">
			<span class="reqular-price"> <span><?php echo $this->__('Open Bid Price:') . ' '?>
			</span><span class="open-price"><?php echo Mage::helper('core')->currency($_product->getOpeningPrice()); ?>
			</span>
			</span>
		</div>
		<div class="countdown">
			<p class="currentvalue">
				<span id="clock<?php echo $i; ?>"></span>
			</p>
		</div> 
		<style>
			.highlight {
			background-color: red;
			}
		</style>
		<div class="price-box" style="text-align: center;">
			<div class="price" id="price<?php echo $_product->getId() ?>">
				<span id="price-box-<?php echo $_product->getId()?>"><?php echo Mage::helper('core')->currency($_product->getCurrentPrice()) ?></span>
			</div>
		</div>
		<div>
			<?php 
			$bidder = $this->getCurrentBidder($_product->getId());
			if ($bidder):
			$bidder = Mage::getModel('customer/customer')->load($bidder[0]['customer_id'])->getName();
			?>
			<span class="bidder"><?php echo $this->__('Bidder:')?> <span class="biddername<?php echo $_product->getId() ?>"><?php echo $bidder ?></span></span>
			<?php endif; ?>
		</div>	
<script>
	jQuery("#clock" + <?php echo $i; ?>).countdown("<?php echo $_productDate ?>")
	.on('update.countdown', function(event){
		var format = '%H:%M:%S';
		if (event.offset.days > 0){
			format = '%-d day%!d ' + format;
		}
		if (event.offset.weeks > 0){
			format = '%-w week%!w ' + format;
		}
		jQuery("#clock" + <?php echo $i; ?>).html(event.strftime(format));
	})
	.on('finish.countdown', function(event) {
		location.reload();
	});
</script>
		<div style="text-align: center; margin-top: 10px;">
			<?php
			$customerSession = $this->getCustomerSession();
			if(!$customerSession->isLoggedIn())
			{
			?>
			<button type="button" title="bid" class="button" id="button<?php echo $_product->getId() ?>" onclick="javascript:alert('Please login')">
				<span>
					<span><?php echo $this->__('Bid')?></span>
				</span>
			</button>
			<?php	
			} 
			else
			{	
			?>
			<form action="#" method="post" class="formbid<?php echo $_product->getId() ?>" id="formbid<?php echo $_product->getId() ?>">
			<?php echo $this->getBlockHtml('formkey') ?>
				<input type="hidden" name="productId" value="<?php echo $_product->getId() ?>" />
				<button type="submit" title="bid" class="button" id="button<?php echo $_product->getId() ?>">
					<span> <span><?php echo $this->__('Bid')?> </span>
					</span>
				</button>
			</form>
			<script>
				jQuery("#formbid<?php echo $_product->getId() ?>").submit(function(event) {
					event.preventDefault();
					jQuery("#button<?php echo $_product->getId() ?>").attr("disabled", true);
					jQuery("#button<?php echo $_product->getId() ?>").fadeOut();
					var values = jQuery(this).serialize();
					jQuery.ajax({
						url: "<?php echo $this->getUrl('bidding/index/bidPost') ?>",
						type: "post",
						data: values,
						success: function(resp){
							resp = jQuery.parseJSON(resp);
							if(resp.action == 'true')
							{
							  jQuery("#button<?php echo $_product->getId() ?>").attr("disabled", false); 
                       		  jQuery("#button<?php echo $_product->getId() ?>").delay(500).fadeIn(50);
                       		  window.socket.emit('send', { message: 1, PI: resp.PI, price: resp.price, bidder: resp.bidder, bidderTable: resp.bidderTable });
                       		  if (resp.reload == 'true')
                       		  {
                           		  location.reload();
                       		  }
								
                       		}
							else if (resp.action == 'false')
							{
								location.reload();
							}
                       		else
                       		{
                       			alert('Please log in to access it');
                       		}
						},
						error: function(){
							alert('faild');
						}
					});
				});
			</script>
			<?php
			}
			?>
		</div>
	</li>
	<?php
	$i++;
	endforeach;
	?>
</ul>
<?php 
else :
?>
<p class="note-msg">
	<?php echo $this->__('There are no products for bid right now')?>
</p>
<?php
endif;
?>