<?php
$_products = $this->getClosedBidding();
if ($_products->count()):
	?>

<div id="messages_product_view">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>
<div class="clickPrice absolute"><span><?php echo $this->__('Sold Numbers')?></span><p><?php echo $_products->count() ?></p></div>
<div class="flexslider">
<ul class="slides">
		<?php
		$i = 1;
		foreach ($_products as $_product):
			$_productDate = date('Y/m/d H:i:s',strtotime($_product->getEndBiddingDate()));
		?>
		<li class="item">
<h3 class="closePrice"><?php echo $this->__('Sold')?> <?php echo Mage::helper('core')->currency($_product->getCurrentPrice()); ?></h3>
			<a
			href="<?php echo $this->getUrl('bidding/closed') ?>"
			class="product-image"> <img
			src="<?php echo $_product->getImageUrl() ?>" />
			<div class="state closed"></div>
		</a>
		<h1 class="product-name">
			<a
			href="<?php echo $this->getUrl('bidding/product/view', array('id'=>$_product->getId())) ?>"
			title="<?php $_product->getName() ?>"><?php echo $_product->getName() ?>
		</a>
	</h1>
	<div class="wideSection">
		<?php 
	$bidder = $this->getCurrentBidder($_product->getId());
if($bidder):		
$bidder = Mage::getModel('customer/customer')->load($bidder[0]['customer_id'])->getName();
	?>
	<div class="Section">
		<div class="winner"><?php echo $this->__('Winner')?> : <?php echo $bidder ?></div>
	</div>
<?php endif; ?>
</div>

</li>


<?php
$i++;
endforeach;
?>
</ul>
</div>
<?php
else :
	?>
<p class="note-msg">
	<?php echo $this->__('There are no products for bid right now')?>
</p>
<?php
endif;
?>
