<?php
$_products = $this->getNextBidding();
if ($_products->count()):
	?>

<div id="messages_product_view">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<div class="flexslider">
<ul class="slides">

		<?php
		$i = 1;
		foreach ($_products as $_product):
			$_productDate = date('Y/m/d H:i:s',strtotime($_product->getEndBiddingDate()));
		?>
		<li class="item ">
<h3 class="blockTitle"><?php echo $this->__('next')?></h3>
			<a
			href="<?php echo $this->getUrl('bidding/product/view', array('id'=>$_product->getId())) ?>"
			class="product-image">
			<div class="clickPrice">
			<?php 	
				$array_cpc = explode('.', $_product->getCpc());
				echo (int)substr($array_cpc[1],0,2) . '&cent;'; 
			?>
			<?php //echo (int)$_product->getOpeningPrice() . '$'; ?></div>
			 <img
			src="<?php echo $_product->getImageUrl() ?>" />
			<div class="state closed"></div>
		</a>
		<h1 class="product-name">
			<a
			href="<?php echo $this->getUrl('bidding/product/view', array('id'=>$_product->getId())) ?>"
			title="<?php $_product->getName() ?>"><?php echo $_product->getName() ?>
		</a>
	</h1>
	<div class="wideSection">
		<div class="Section">
	<span class="winner"><?php echo $this->__('opening price is')?> </span><?php echo Mage::helper('core')->currency($_product->getOpeningPrice()); ?>
	</div>
</div>
</li>

<?php
$i++;
endforeach;
?>
</ul>
</div>
<?php
else :
	?>
<p class="note-msg">
	<?php echo $this->__('There are no products for bid right now')?>
</p>
<?php
endif;
?>
