<?php
$products = $this->getWinProducts();
?>
<div class="my-account">
	<div class="dashboard">
		<div class="page-title">
			<h1>
			<?php echo $this->__('Winner Dashboard')?>
			</h1>
		</div>
		<div class="fieldset">
			<h2 class="legend">
			<?php echo $this->__('Winning Products')?>
			</h2>
			<?php if  ($products->getData()): ?>
			<table class="data-table" id="my-orders-table">
				<thead>
					<tr class="first last">
						<th><?php echo $this->__('Product Name')?></th>
						<th><?php echo $this->__('Final Price')?></th>
						<th>&nbsp;</th>
					</tr>
				</thead>
				<tbody>
				<?php
				foreach ($products as $product)
				{
					$_product = Mage::getModel('catalog/product')->load($product->getProductId());
					$_product->setPrice($_product->getCurrentPrice());
					$_product->save();
					?>
					<tr>
						<td><?php echo $_product->getName() ?></td>
						<td><?php echo Mage::helper('core')->currency($_product->getCurrentPrice()) ?>
						</td>
						<td style="text-align: center"><?php
						if(!$product->getBought())
						{
							?> <?php $buttonTitle = $this->__('Add to Cart'); ?> <?php if($_product->isSaleable()): ?>
							<div class="add-to-cart">
								<form action="<?php echo $this->getSubmitUrl($_product) ?>"
									method="post" id="product_addtocart_form_<?php echo $_product->getId() ?>"
									<?php if($_product->getOptions()): ?>
									enctype="multipart/form-data" <?php endif; ?>>
									<?php echo $this->getBlockHtml('formkey') ?>
									<button type="button" title="<?php echo $buttonTitle ?>"
										class="button btn-cart" onclick="document.getElementById('product_addtocart_form_<?php echo $_product->getId() ?>').submit()">
										<span><span><?php echo $buttonTitle ?> </span> </span>
									</button>
								</form>
								<?php echo $this->getChildHtml('', true, true) ?>
							</div> <?php 
							endif;
						}
						?>
						</td>

					</tr>

    <?php
				}
				?>
				</tbody>
			</table>
			<?php else: ?>
			<p>
			<?php echo $this->__('You didn\'t win any product till now')?>
			</p>
			<?php endif; ?>
		</div>
	</div>
</div>
